[package]
name = "event-stream"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
rdkafka = { version = "0.25", features = ["cmake-build"] }
thiserror = "1.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"